[package]
name = "shrots"
version = "0.1.1"
edition = "2021"

[dependencies]
fltk = "1.4.24"
fltk-grid = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.116"
clap = { version = "4.5.4", features = ["derive"] }
