[general]
width=1800
height=1000
opacity=0.8
columns=3
border=2

[colors]
background=0x222222
foreground=0xFFFFFF
border=0x64DBFF
shrot=0x64DBFF
about=0xF1F1F1

[shrots]
Neovim = [
    {bind = "h, j, k, l", about = "Move around"},
    {bind = "gg, G", about = "Jump to top / bottom"},
    {bind = "CTRL + w + h, j, k, l", about = "Navigate panes"},
    {bind = "CTRL + w + s", about = "Split horizontal"},
    {bind = "CTRL + w + v", about = "Split vertical"},
    {bind = "CTLR + N", about = "Open multi-cursor"},
    {bind = "CTRL + ARROW", about = "Multi-cursor select"},
    {bind = "S", about = "Surround prefix"},
    {bind = "CTRL + t", about = "Open NvimTree"},
    {bind = "CTRL + h", about = "Search and replace"},
]
Vimium = [
    {bind = "h, j, k, l", about = "Move left, down, up, right  around"},
    {bind = "J, K", about = "Move left / right between tabs"},
    {bind = "H, L", about = "Move back / forward in history"},
    {bind = "gg", about = "Jump to top"},
    {bind = "G", about = "Jump to bottom"},
    {bind = "o", about = "Open search"},
    {bind = "O", about = "Open search, for new tab"},
    {bind = "t", about = "Create new tab"},
    {bind = "x", about = "Close a tab"},
    {bind = "/", about = "Search in the page"},
    {bind = "f", about = "Show links to open"},
    {bind = "F", about = "Show links to open, for new tab"},
    {bind = "r", about = "Reload the page"},
    {bind = "u, d", about = "Up / down half a page"},
    {bind = "<, >", about = "Move tab left / right"}
]
I3 = [
    {bind = "WIN + d", about = "Open Drun"},
    {bind = "WIN + D", about = "Open run"},
    {bind = "WIN + 1, 2, 3", about = "Switch panes"},
    {bind = "WIN + SHIFT + 1, 2, 3", about = "Move panes"},
    {bind = "WIN + SHIFT + ARROW", about = "Move panes"},
    {bind = "WIN + R", about = "Reload I3 config"},
    {bind = "WIN + S", about = "Run flameshot"},
    {bind = "WIN + A", about = "Run shrots"},
]
Flameshot = [
    {bind = "CTRL + c", about = "Copy image"},
    {bind = "CTRL + x", about = "Pin image to screen"},
]
Tmux = [
    {bind = "CTRL + q", about = "Split horizontal"},
    {bind = "CTRL + w", about = "Split vertical"},
    {bind = "ALT + ARROW", about = "Move within panes"},
    {bind = "ALT + f + SHIFT + ARROW", about = "Move panes"},
    {bind = "ALT + f + e", about = "Exit pane"},
    {bind = "ALT + f + f", about = "Find in pane"},
    {bind = "ALT + f + [", about = "Enter copy mode"},
    {bind = "ALT + f + z", about = "Focus on pane"},

]
